Class added and extended class and constructers
Yilikal250/Ruby-oop pull request #1
Opened 2023-01-04 20:39 UTC by Yilikal250

- Created class Person with the following:
   - [ ] Instance vars: @id, @name, and @age.
   - [ ] Constructor with name, age, and parent permission as a parameter. name and parent permission are optional and have a 
   default 
   - [ ] values of "Unknown" and true.
   - [ ] Getters for @id, @name, and @age.
   - [ ] Setters for @name and @age.
   - [ ] Private method is_of_age? that returns true if @age is greater or equal to 18 and false otherwise.
   - [ ] Public method can_use_services? that returns true if a person is of age or if they have permission from parents.
-   Created class Student with the following
    - [ ] Inherits from Person.
    - [ ] Constructor extends parent's constructor by adding @classroom and a parameter for it.
    - [ ] Method play_hooky that returns "¯\(ツ)/¯".
-  Created class Teacher with the following
    - [ ] Inherits from Person.
    - [ ] Constructor extends parent's constructor by adding @specialization and a parameter for it.
    - [ ] Override can_use_services? so it always returns true.

2023-01-04 21:35 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @Yilikal250 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow Gitflow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-04 21:35 UTC, tresorsawasawa commented on student.rb
> +    super(name, age, parent_permission, classroom)
- [ ] As the `Student` class inherits from the `Person` class and the `Person` class doesn't have the `classroom` parameter. I think it would be good if you update the `super(name, age, parent_permission, classroom)` method to this `super(name, age, parent_permission)` by removing the `classroom` parameter.
```ruby
# bad
super(name, age, parent_permission, classroom)

# Good
super(name, age, parent_permission)
```

2023-01-04 21:35 UTC, tresorsawasawa commented on teacher.rb
> +  end
- [ ] As the `Teacher` class inherits from the `Person` class and the `Person` class doesn't have the `specialization` parameter. I think it would be good if you update the `super(name, age, parent_permission, classroom, specialization)` method to this `super(name, age, parent_permission)` by removing the `specialization` parameter.
```ruby
# bad
super(name, age, parent_permission, classroom, specialization)

# Good
super(name, age, parent_permission)
```

2023-01-04 21:35 UTC, tresorsawasawa commented on README.md
> +-->
- [ **OPTIONAL** ] As it mentioned in this template, I thing it would be good if you remove all the comments and instructions.

2023-01-04 22:10 UTC, t-yanick requested changes
Hi @Yilikal250 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

You can also consider:
- Using more descriptive names for your future branches. `feature` is not a very good branch name

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-04 22:10 UTC, t-yanick commented on teacher.rb
> +  end
- [ ] The previous reviewer suggested you update the s`uper(name, age, parent_permission, classroom, specialization) `method to `super(name, age, parent_permission) `since `Teacher` class inherits from `Person` class and the `Person` class does not have the `specialization` parameter. That I can see you have not done so. Please kindly effect this change.

2023-01-04 22:10 UTC, t-yanick commented on student.rb
> +    super(name, age, parent_permission, classroom)
- [ ] You have the same issue like what I mentioned below. Kindly apply the update proposed by the previous reviewer.

2023-01-05 06:19 UTC, OLIPLICHE approved these changes
Hi @Yilikal250, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Highlights
- Applied the change requested👏 👏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-05 06:24 UTC, merged