Decorators added
Yilikal250/Ruby-oop pull request #2
Opened 2023-01-05 19:37 UTC by Yilikal250

- Created a class Nameable.
- [ ] Implemented a method called correct_name that will raise a NotImplementedError.
- [ ] Turned Person class to Nameable

- Made sure that the Person class inherits from Nameable
- [ ] Make sure that this class has a method correct_name implemented. It should simply return the name attribute.
       Prepare base Decorator
- [ ] Make sure that it inherits from Nameable.

- In the constructor i assigned a nameable object from params to an instance variable.
- [ ] Implemented the correct_name method that returns the result of the correct_name method of the @nameable.
- [ ] Prepared CapitalizeDecorator and TrimmerDecorator

- For the CapitalizeDecorator:
- [ ] Created a class that inherits from the base Decorator class.
- [ ] Implemented a method correct_name that capitalizes the output of @nameable.correct_name.

- For the TrimmerDecorator:
- [ ] Created a class that inherits from the base Decorator class.
- [ ] Implemented a method correct_name that makes sure that the output of @nameable.correct_name has a maximum of 10 characters. If it's longer it should trim the word.

2023-01-05 20:16 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @Yilikal250 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-05 20:16 UTC, tresorsawasawa commented on person.rb
>    end
- [ ] Good job  inheriting your `Person` class from `Nameable` class as mentioned in the requirements. But I think it would be better if you firstly import the file itself. As both files are in the same directory, you can use `require_relative`  to import it.

- [ ] Also remember to remove this `super(name)` here as the `Nameable` class doesn't have any parameter or variable named `name` and this `super(name)` raises an error when trying to test your app.

2023-01-05 20:16 UTC, tresorsawasawa commented on decorator.rb
> +  end
- [ ] Kindly make sure the `nameable` parameter from the the constructor method doesn't have any default value, as it is not mentioned anywhere in the requirements to assign a value. I suggest you you leave it without any default value i.e.:
```ruby
  ...
  def initialize(nameable)
  ...
```

- [ ] I think it would be better if you define the  `:nameable` attribute as both a `getter` and a `setter` i.e you can use the `attr_accessor :nameable` for that. This will make that variable to be easily accessible (read/write) by outside users without having to write class accessor methods.

2023-01-05 20:16 UTC, tresorsawasawa commented on decorator.rb
> +  end
- [ ]  Kindly make sure you remember to import the `nameable.rb` file containing the class to inherit from. As both files are in the same directory, you can use `require_relative`  to import it.

2023-01-05 20:16 UTC, tresorsawasawa commented on capitalize_decorator.rb
> +    @nameable.correct_name.capitalize
- [ ]  Kindly make sure you remember to import the `decorator.rb` file containing the class to inherit from. As both files are in the same directory, you can use `require_relative`  to import it.

2023-01-05 20:16 UTC, tresorsawasawa commented on trimmer_decorator.rb
> +    if @nameable.correct_name.length <= 10
- [ ] As I mentioned in the previous comments, kindly make sure you remember to import the `decorator.rb` file containing the class to inherit from. As both files are in the same directory, you can use `require_relative`  to import it.

2023-01-05 20:16 UTC, tresorsawasawa commented on trimmer_decorator.rb
> +end
**NOTTICE:** It would be good once you have implemented all the above changes to run all the below commands in order to check if your app is working as expected before requesting a new review:
```ruby
 person = Person.new(22, 'maximilianus')
 person.correct_name
 capitalizedPerson = CapitalizeDecorator.new(person)
 capitalizedPerson.correct_name
 capitalizedTrimmedPerson = TrimmerDecorator.new(capitalizedPerson)
 capitalizedTrimmedPerson.correct_name
```

2023-01-06 14:20 UTC, addod19 requested changes
### Hi @Yilikal250, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- [ ] Great job addressing some of the comments made by the previous code reviewer :100: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-06 14:20 UTC, addod19 commented on decorator.rb
> +class Decorator < Nameable
- [ ] As mentioned by the previous code reviewer, we were advised to make the `nameable` variable both has access to read/write operation. We have not implemented that, we can achieve by using the `attr_accessor` instead of creating methods for getter and setter

2023-01-06 14:20 UTC, addod19 commented on person.rb
> +require './trimmer_decorator'
- [ ] Also, we were asked by the previous code reviewer to use `require_relative` when dealing with files in our current directory. We can only use `require` when dealing with files or packages in our gemfiles

2023-01-06 20:51 UTC, VICTOR-CHUKWU approved these changes
Hi @Yilikal250 , 
# STATUS: APPROVED! 🥇 💯 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- [ ] All linters passed

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-06 21:00 UTC, merged